### ISSUE TITLE
All communication from to the light server should be through the same connection 

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#12]
I think there was one in the manager?

**Comment by Zetro** [comment]
I remembered a thing now about HTTPConnection now. It might be better to have separate connections for separate components since its state based and a request shouldn't be sent before reading the response of the previous request. So it will throw exceptions if games and config can send two requests simultaneously

**Comment by wamanuz** [comment]
Stupid. Won't fix.
