### ISSUE TITLE
Memory should not initiate if number of bricks are odd

### ISSUE THREAD

**Issue by hleskela** [smab/playhouse-web#42]
A 3x3 playfield made three odd ones, so the config interface should take proper actions when a user tries to init an odd number of bricks.

**Comment by migomipo** [comment]
Refusing to start would not be a good way to handle the situation. A more sensible approach would be to turn off one of the corner lights, which brings the number of active lights down to an even number.

**Comment by Zetro** [comment]
Possible actions that I can think of:
- Turn off a light as @migomipo suggested and give a warning/info message
- Turn an entire row or column instead of a single light
- Give an error message and revert to the previous size or an even default size (when changing from config/game)
- Allow one brick without a pair and make sure the game finishes when all pairs are found

**Comment by FireyFly** [comment]
Closing per the above commit (opts for the third option suggested by @Zetro).

**Comment by migomipo** [comment]
"Solution" 3 is a very impractical solution for buildings with an odd amount of lights. Why arbitrarily force the server to use a size that's different from the actual building lamp grid size? If the building lamp grid is 5x5, then 5x5 should be a permitted size for this game too. Turning off 1 (one) corner light is a much better approach IMO.
