### ISSUE TITLE
Big panic!

### ISSUE THREAD

**Issue by webbmastern** [smab/playhouse-web#43]
Went by akvariet this morning with Hannes and apparently someone has tipped the lamp array and shattered five lamps. We need to talk to Håkan about this asap!

**Comment by hleskela** [comment]
I just woke up due to lack of sleep tonight, so I don't think it was you and I who made the discovery. But thanks for the mentioning.
Will update my status in the protocol, won't make it in time for meeting.

Mvh Hannes Leskelä

1 apr 2014 kl. 10:16 skrev "webbmastern" <notifications@github.com<mailto:notifications@github.com>>:

Went by akvariet this morning with Hannes and apparently someone has tipped the lamp array and shattered five lamps. We need to talk to Håkan about this asap!

**Comment by webbmastern** [comment]
I fixed it
