### ISSUE TITLE
[animation] Should be able to center animation vertically 

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#60]
If horizontally is already an option.

**Comment by Zetro** [comment]
And I still suggest that these are implemented using a simple x,y offset/translation where 0,0 is and make it accessable for all games

**Comment by clid** [comment]
Fixed in https://github.com/smab/playhouse-web/commit/ee1211dd1b3d9bc66f5df465e7307e524e7a5e30
Gifs can now be centered and offset in both axes, and lamps should now reset properly when offset or gif-file has changed, and not be left at their previous color (though not fixed for the webpage, since it's gonna be removed anyway). These two options also work together.

Might need testing on real lamps.

Since offset for gif animations works by changing both what lamps to change and what pixels in the gif to read, thus able to offset images both smaller and larger than the grid and in both directions (left/right for x-axis etc), it would have to be changed a lot to abstract to all games. Create a new issue for that if it is needed.
