### ISSUE TITLE
[games] Move the queue button to the top bar 

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#68]
We discussed it before, and IIRC it was a popular suggestion.  

Don't forget to remove the bottom bar as well.

**Comment by webbmastern** [comment]
Moved the queue button to the top. Didn't merge it with the message top bar, and instead moved the queue button under with a little space between so it may be easier to read. Thought this might be a good solution since sometimes it could be good to have them separated.
If you don't like the space, just change the css-file.
